data_generic_cache_providers:
  providers:
     - 'redis'
     - 'mongodb'
     - 'localmemory'

data_generic_cache_redis:
  host: '127.0.0.1'
  portNumber: 6379

data_generic_cache_mongodb:
  host: '127.0.0.1'
  portNumber: 27017